// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJfpx_mBJdtDgsTmd9JppVjsxpt95fj3w',
    appId: '1:593611426236:android:9cd87a5138257a308083b9',
    messagingSenderId: '593611426236',
    projectId: 'miltech-c3007',
    storageBucket: 'miltech-c3007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVQlN5Mcyg5i2j1Fv7D7en9yscUKivGk',
    appId: '1:593611426236:ios:25aa849d8ab9826d8083b9',
    messagingSenderId: '593611426236',
    projectId: 'miltech-c3007',
    storageBucket: 'miltech-c3007.firebasestorage.app',
    androidClientId: '593611426236-epbob3ebnf6cjgdi4003jabfbkcbgjq5.apps.googleusercontent.com',
    iosClientId: '593611426236-vdp2b9v965bhqdmii1bncssa6nsiuot4.apps.googleusercontent.com',
    iosBundleId: 'com.miltech.miltech',
  );

}