// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBnbDtKZG8iuSJfb3NiXpV9Fv8e_Zinc',
    appId: '1:343741785039:android:5b5437ba5302378e06e8ba',
    messagingSenderId: '343741785039',
    projectId: 'rewaldo-app',
    storageBucket: 'rewaldo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduAy4F19WuJJYaz8nS19vISm2FuLwx50',
    appId: '1:343741785039:ios:02925a01dac9385306e8ba',
    messagingSenderId: '343741785039',
    projectId: 'rewaldo-app',
    storageBucket: 'rewaldo-app.firebasestorage.app',
    androidClientId: '343741785039-gttgi7ig5pbce4bp472kr7nu6d5h38ds.apps.googleusercontent.com',
    iosClientId: '343741785039-347u4e0lm97in3knogrupct31usacivc.apps.googleusercontent.com',
    iosBundleId: 'com.mlitech.rewaldo.customer',
  );
}