class CountryModelData {
  final String name;
  final String flag;
  final String code; // নতুন যোগ করা: 2-digit ISO code
  final double lat;
  final double lng;

  CountryModelData({
    required this.name,
    required this.flag,
    required this.code,
    required this.lat,
    required this.lng,
  });

  factory CountryModelData.fromJson(Map<String, dynamic> json) {
    final coordinates = json['coordinates'] as Map<String, dynamic>;
    return CountryModelData(
      name: json['name'] as String,
      flag: json['flag'] as String,
      code: json['code'] as String, // JSON থেকে code নেওয়া
      lat: (coordinates['latitude'] as num).toDouble(),
      lng: (coordinates['longitude'] as num).toDouble(),
    );
  }

  @override
  String toString() {
    return 'Country(name: $name, code: $code, flag: $flag, lat: $lat, lng: $lng)';
  }
}

final List<CountryModelData> countries = [
  CountryModelData(name: "Afghanistan", flag: "https://flagcdn.com/af.svg", code: "AF", lat: 33.93911, lng: 67.709953),
  CountryModelData(name: "Albania", flag: "https://flagcdn.com/al.svg", code: "AL", lat: 41.1533, lng: 20.1683),
  CountryModelData(name: "Algeria", flag: "https://flagcdn.com/dz.svg", code: "DZ", lat: 28.0339, lng: 1.6596),
  CountryModelData(name: "Andorra", flag: "https://flagcdn.com/ad.svg", code: "AD", lat: 42.5078, lng: 1.5211),
  CountryModelData(name: "Angola", flag: "https://flagcdn.com/ao.svg", code: "AO", lat: -11.2027, lng: 17.8733),
  CountryModelData(name: "Antigua and Barbuda", flag: "https://flagcdn.com/ag.svg", code: "AG", lat: 17.0608, lng: -61.7964),
  CountryModelData(name: "Argentina", flag: "https://flagcdn.com/ar.svg", code: "AR", lat: -38.4161, lng: -63.6167),
  CountryModelData(name: "Armenia", flag: "https://flagcdn.com/am.svg", code: "AM", lat: 40.0691, lng: 45.0382),
  CountryModelData(name: "Australia", flag: "https://flagcdn.com/au.svg", code: "AU", lat: -25.2744, lng: 133.7751),
  CountryModelData(name: "Austria", flag: "https://flagcdn.com/at.svg", code: "AT", lat: 47.5162, lng: 14.5501),
  CountryModelData(name: "Azerbaijan", flag: "https://flagcdn.com/az.svg", code: "AZ", lat: 40.1431, lng: 47.5769),
  CountryModelData(name: "Bahamas", flag: "https://flagcdn.com/bs.svg", code: "BS", lat: 25.0343, lng: -77.3963),
  CountryModelData(name: "Bahrain", flag: "https://flagcdn.com/bh.svg", code: "BH", lat: 25.9304, lng: 50.6378),
  CountryModelData(name: "Bangladesh", flag: "https://flagcdn.com/bd.svg", code: "BD", lat: 23.685, lng: 90.3563),
  CountryModelData(name: "Barbados", flag: "https://flagcdn.com/bb.svg", code: "BB", lat: 13.1939, lng: -59.5432),
  CountryModelData(name: "Belarus", flag: "https://flagcdn.com/by.svg", code: "BY", lat: 53.9, lng: 27.5667),
  CountryModelData(name: "Belgium", flag: "https://flagcdn.com/be.svg", code: "BE", lat: 50.8503, lng: 4.3517),
  CountryModelData(name: "Belize", flag: "https://flagcdn.com/bz.svg", code: "BZ", lat: 17.1899, lng: -88.4976),
  CountryModelData(name: "Benin", flag: "https://flagcdn.com/bj.svg", code: "BJ", lat: 9.3075, lng: 2.3158),
  CountryModelData(name: "Bhutan", flag: "https://flagcdn.com/bt.svg", code: "BT", lat: 27.5142, lng: 90.4336),
  CountryModelData(name: "Bolivia", flag: "https://flagcdn.com/bo.svg", code: "BO", lat: -16.2902, lng: -63.5887),
  CountryModelData(name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg", code: "BA", lat: 43.8486, lng: 18.3564),
  CountryModelData(name: "Botswana", flag: "https://flagcdn.com/bw.svg", code: "BW", lat: -22.3285, lng: 24.6849),
  CountryModelData(name: "Brazil", flag: "https://flagcdn.com/br.svg", code: "BR", lat: -14.235, lng: -51.9253),
  CountryModelData(name: "Brunei", flag: "https://flagcdn.com/bn.svg", code: "BN", lat: 4.5353, lng: 114.7277),
  CountryModelData(name: "Bulgaria", flag: "https://flagcdn.com/bg.svg", code: "BG", lat: 42.7333, lng: 25.4858),
  CountryModelData(name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg", code: "BF", lat: 12.2383, lng: -1.5616),
  CountryModelData(name: "Cabo Verde", flag: "https://flagcdn.com/cv.svg", code: "CV", lat: 16.5384, lng: -23.0418),
  CountryModelData(name: "Cambodia", flag: "https://flagcdn.com/kh.svg", code: "KH", lat: 12.5657, lng: 104.991),
  CountryModelData(name: "Cameroon", flag: "https://flagcdn.com/cm.svg", code: "CM", lat: 3.848, lng: 11.5021),
  CountryModelData(name: "Canada", flag: "https://flagcdn.com/ca.svg", code: "CA", lat: 56.1304, lng: -106.3468),
  CountryModelData(name: "Central African Republic", flag: "https://flagcdn.com/cf.svg", code: "CF", lat: 6.6111, lng: 20.9394),
  CountryModelData(name: "Chad", flag: "https://flagcdn.com/td.svg", code: "TD", lat: 15.4542, lng: 18.7322),
  CountryModelData(name: "Chile", flag: "https://flagcdn.com/cl.svg", code: "CL", lat: -35.6751, lng: -71.543),
  CountryModelData(name: "China", flag: "https://flagcdn.com/cn.svg", code: "CN", lat: 35.8617, lng: 104.1954),
  CountryModelData(name: "Colombia", flag: "https://flagcdn.com/co.svg", code: "CO", lat: 4.5709, lng: -74.2973),
  CountryModelData(name: "Comoros", flag: "https://flagcdn.com/km.svg", code: "KM", lat: -11.875, lng: 43.8722),
  CountryModelData(name: "Costa Rica", flag: "https://flagcdn.com/cr.svg", code: "CR", lat: 9.7489, lng: -83.7534),
  CountryModelData(name: "Croatia", flag: "https://flagcdn.com/hr.svg", code: "HR", lat: 45.1, lng: 15.2),
  CountryModelData(name: "Cuba", flag: "https://flagcdn.com/cu.svg", code: "CU", lat: 21.5218, lng: -77.7812),
  CountryModelData(name: "Cyprus", flag: "https://flagcdn.com/cy.svg", code: "CY", lat: 35.1264, lng: 33.4299),
  CountryModelData(name: "Czech Republic", flag: "https://flagcdn.com/cz.svg", code: "CZ", lat: 49.8175, lng: 15.472),
  CountryModelData(name: "Côte d'Ivoire", flag: "https://flagcdn.com/ci.svg", code: "CI", lat: 7.5398, lng: -5.5471),
  CountryModelData(name: "Denmark", flag: "https://flagcdn.com/dk.svg", code: "DK", lat: 56.2639, lng: 9.5018),
  CountryModelData(name: "Djibouti", flag: "https://flagcdn.com/dj.svg", code: "DJ", lat: 11.8251, lng: 42.5903),
  CountryModelData(name: "Dominica", flag: "https://flagcdn.com/dm.svg", code: "DM", lat: 15.4148, lng: -61.3701),
  CountryModelData(name: "Dominican Republic", flag: "https://flagcdn.com/do.svg", code: "DO", lat: 18.7357, lng: -70.1627),
  CountryModelData(name: "Democratic People's Republic of Korea", flag: "https://flagcdn.com/kp.svg", code: "KP", lat: 40.3399, lng: 127.5101),
  CountryModelData(name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/cd.svg", code: "CD", lat: -4.0383, lng: 21.7587),
  CountryModelData(name: "Eswatini", flag: "https://flagcdn.com/sz.svg", code: "SZ", lat: -26.5225, lng: 31.4659),
  CountryModelData(name: "Ecuador", flag: "https://flagcdn.com/ec.svg", code: "EC", lat: -1.8312, lng: -78.1834),
  CountryModelData(name: "Egypt", flag: "https://flagcdn.com/eg.svg", code: "EG", lat: 26.8206, lng: 30.8025),
  CountryModelData(name: "El Salvador", flag: "https://flagcdn.com/sv.svg", code: "SV", lat: 13.7942, lng: -88.8965),
  CountryModelData(name: "Equatorial Guinea", flag: "https://flagcdn.com/gq.svg", code: "GQ", lat: 1.6508, lng: 10.2679),
  CountryModelData(name: "Eritrea", flag: "https://flagcdn.com/er.svg", code: "ER", lat: 15.1794, lng: 39.7823),
  CountryModelData(name: "Estonia", flag: "https://flagcdn.com/ee.svg", code: "EE", lat: 58.5953, lng: 25.0136),
  CountryModelData(name: "Fiji", flag: "https://flagcdn.com/fj.svg", code: "FJ", lat: -16.5782, lng: 179.1947),
  CountryModelData(name: "Finland", flag: "https://flagcdn.com/fi.svg", code: "FI", lat: 61.9241, lng: 25.7482),
  CountryModelData(name: "France", flag: "https://flagcdn.com/fr.svg", code: "FR", lat: 46.6034, lng: 1.8883),
  CountryModelData(name: "Gabon", flag: "https://flagcdn.com/ga.svg", code: "GA", lat: -0.8037, lng: 11.6094),
  CountryModelData(name: "Gambia", flag: "https://flagcdn.com/gm.svg", code: "GM", lat: 13.4432, lng: -15.3101),
  CountryModelData(name: "Georgia", flag: "https://flagcdn.com/ge.svg", code: "GE", lat: 42.3154, lng: 43.3569),
  CountryModelData(name: "Germany", flag: "https://flagcdn.com/de.svg", code: "DE", lat: 51.1657, lng: 10.4515),
  CountryModelData(name: "Greece", flag: "https://flagcdn.com/gr.svg", code: "GR", lat: 39.0742, lng: 21.8243),
  CountryModelData(name: "Guatemala", flag: "https://flagcdn.com/gt.svg", code: "GT", lat: 13.4425, lng: -90.5296),
  CountryModelData(name: "Haiti", flag: "https://flagcdn.com/ht.svg", code: "HT", lat: 18.9712, lng: -72.2852),
  CountryModelData(name: "Honduras", flag: "https://flagcdn.com/hn.svg", code: "HN", lat: 13.9241, lng: -83.3561),
  CountryModelData(name: "Hungary", flag: "https://flagcdn.com/hu.svg", code: "HU", lat: 47.1625, lng: 19.5033),
  CountryModelData(name: "India", flag: "https://flagcdn.com/in.svg", code: "IN", lat: 20.5937, lng: 78.9629),
  CountryModelData(name: "Indonesia", flag: "https://flagcdn.com/id.svg", code: "ID", lat: -0.7893, lng: 113.9213),
  CountryModelData(name: "Iran", flag: "https://flagcdn.com/ir.svg", code: "IR", lat: 32.4279, lng: 53.688),
  CountryModelData(name: "Iraq", flag: "https://flagcdn.com/iq.svg", code: "IQ", lat: 33.2232, lng: 43.6793),
  CountryModelData(name: "Ireland", flag: "https://flagcdn.com/ie.svg", code: "IE", lat: 53.1424, lng: -7.6921),
  CountryModelData(name: "Israel", flag: "https://flagcdn.com/il.svg", code: "IL", lat: 31.468, lng: 35.1328),
  CountryModelData(name: "Italy", flag: "https://flagcdn.com/it.svg", code: "IT", lat: 41.8719, lng: 12.5674),
  CountryModelData(name: "Iceland", flag: "https://flagcdn.com/is.svg", code: "IS", lat: 64.9631, lng: -19.0208),
  CountryModelData(name: "Jamaica", flag: "https://flagcdn.com/jm.svg", code: "JM", lat: 18.1096, lng: -77.2975),
  CountryModelData(name: "Japan", flag: "https://flagcdn.com/jp.svg", code: "JP", lat: 36.2048, lng: 138.2529),
  CountryModelData(name: "Jordan", flag: "https://flagcdn.com/jo.svg", code: "JO", lat: 30.5852, lng: 36.2384),
  CountryModelData(name: "Kazakhstan", flag: "https://flagcdn.com/kz.svg", code: "KZ", lat: 48.0196, lng: 66.9237),
  CountryModelData(name: "Kenya", flag: "https://flagcdn.com/ke.svg", code: "KE", lat: -1.2921, lng: 36.8219),
  CountryModelData(name: "Kiribati", flag: "https://flagcdn.com/ki.svg", code: "KI", lat: -3.3704, lng: 171.21),
  CountryModelData(name: "Korea, North", flag: "https://flagcdn.com/kp.svg", code: "KP", lat: 40.3399, lng: 127.5101),
  CountryModelData(name: "Korea, South", flag: "https://flagcdn.com/kr.svg", code: "KR", lat: 35.9078, lng: 127.7669),
  CountryModelData(name: "Kuwait", flag: "https://flagcdn.com/kw.svg", code: "KW", lat: 29.3759, lng: 47.9774),
  CountryModelData(name: "Kyrgyzstan", flag: "https://flagcdn.com/kg.svg", code: "KG", lat: 41.2044, lng: 74.7661),
  CountryModelData(name: "Laos", flag: "https://flagcdn.com/la.svg", code: "LA", lat: 19.8563, lng: 102.4955),
  CountryModelData(name: "Latvia", flag: "https://flagcdn.com/lv.svg", code: "LV", lat: 56.8796, lng: 24.6032),
  CountryModelData(name: "Lebanon", flag: "https://flagcdn.com/lb.svg", code: "LB", lat: 33.8547, lng: 35.8623),
  CountryModelData(name: "Lesotho", flag: "https://flagcdn.com/ls.svg", code: "LS", lat: -29.6091, lng: 28.2336),
  CountryModelData(name: "Liberia", flag: "https://flagcdn.com/lr.svg", code: "LR", lat: 9.4295, lng: -9.4295),
  CountryModelData(name: "Libya", flag: "https://flagcdn.com/ly.svg", code: "LY", lat: 26.3351, lng: 17.2283),
  CountryModelData(name: "Liechtenstein", flag: "https://flagcdn.com/li.svg", code: "LI", lat: 47.1415, lng: 9.5215),
  CountryModelData(name: "Lithuania", flag: "https://flagcdn.com/lt.svg", code: "LT", lat: 55.1694, lng: 23.8813),
  CountryModelData(name: "Luxembourg", flag: "https://flagcdn.com/lu.svg", code: "LU", lat: 49.6117, lng: 6.13),
  CountryModelData(name: "Madagascar", flag: "https://flagcdn.com/mg.svg", code: "MG", lat: -18.7669, lng: 46.8691),
  CountryModelData(name: "Malawi", flag: "https://flagcdn.com/mw.svg", code: "MW", lat: -13.2543, lng: 34.3015),
  CountryModelData(name: "Malaysia", flag: "https://flagcdn.com/my.svg", code: "MY", lat: 4.2105, lng: 101.9758),
  CountryModelData(name: "Maldives", flag: "https://flagcdn.com/mv.svg", code: "MV", lat: 3.2028, lng: 73.2207),
  CountryModelData(name: "Mali", flag: "https://flagcdn.com/ml.svg", code: "ML", lat: 17.5707, lng: -3.9962),
  CountryModelData(name: "Malta", flag: "https://flagcdn.com/mt.svg", code: "MT", lat: 35.9375, lng: 14.3754),
  CountryModelData(name: "Marshall Islands", flag: "https://flagcdn.com/mh.svg", code: "MH", lat: 7.1315, lng: 171.1845),
  CountryModelData(name: "Mauritania", flag: "https://flagcdn.com/mr.svg", code: "MR", lat: 21.0079, lng: -10.9408),
  CountryModelData(name: "Mauritius", flag: "https://flagcdn.com/mu.svg", code: "MU", lat: -20.348404, lng: 57.552152),
  CountryModelData(name: "Mexico", flag: "https://flagcdn.com/mx.svg", code: "MX", lat: 23.6345, lng: -102.5528),
  CountryModelData(name: "Micronesia (Federated States of)", flag: "https://flagcdn.com/fm.svg", code: "FM", lat: 6.7776, lng: 158.0152),
  CountryModelData(name: "Moldova", flag: "https://flagcdn.com/md.svg", code: "MD", lat: 47.4116, lng: 28.3699),
  CountryModelData(name: "Monaco", flag: "https://flagcdn.com/mc.svg", code: "MC", lat: 43.7333, lng: 7.4167),
  CountryModelData(name: "Mongolia", flag: "https://flagcdn.com/mn.svg", code: "MN", lat: 46.8625, lng: 103.8467),
  CountryModelData(name: "Montenegro", flag: "https://flagcdn.com/me.svg", code: "ME", lat: 42.4411, lng: 19.2636),
  CountryModelData(name: "Morocco", flag: "https://flagcdn.com/ma.svg", code: "MA", lat: 31.7917, lng: -7.0926),
  CountryModelData(name: "Mozambique", flag: "https://flagcdn.com/mz.svg", code: "MZ", lat: -18.6657, lng: 35.5296),
  CountryModelData(name: "Myanmar", flag: "https://flagcdn.com/mm.svg", code: "MM", lat: 21.9139, lng: 95.956),
  CountryModelData(name: "Namibia", flag: "https://flagcdn.com/na.svg", code: "NA", lat: -22.9576, lng: 18.4904),
  CountryModelData(name: "Nauru", flag: "https://flagcdn.com/nr.svg", code: "NR", lat: -0.5228, lng: 166.9315),
  CountryModelData(name: "Nepal", flag: "https://flagcdn.com/np.svg", code: "NP", lat: 28.3949, lng: 84.124),
  CountryModelData(name: "Netherlands", flag: "https://flagcdn.com/nl.svg", code: "NL", lat: 52.3676, lng: 4.9041),
  CountryModelData(name: "New Zealand", flag: "https://flagcdn.com/nz.svg", code: "NZ", lat: -40.9006, lng: 174.886),
  CountryModelData(name: "Nicaragua", flag: "https://flagcdn.com/ni.svg", code: "NI", lat: 12.8654, lng: -85.2072),
  CountryModelData(name: "Niger", flag: "https://flagcdn.com/ne.svg", code: "NE", lat: 17.6078, lng: 8.0817),
  CountryModelData(name: "Nigeria", flag: "https://flagcdn.com/ng.svg", code: "NG", lat: 9.082, lng: 8.6753),
  CountryModelData(name: "North Macedonia", flag: "https://flagcdn.com/mk.svg", code: "MK", lat: 41.6086, lng: 21.7453),
  CountryModelData(name: "Norway", flag: "https://flagcdn.com/no.svg", code: "NO", lat: 60.472, lng: 8.4689),
  CountryModelData(name: "Oman", flag: "https://flagcdn.com/om.svg", code: "OM", lat: 21.4735, lng: 55.9754),
  CountryModelData(name: "Pakistan", flag: "https://flagcdn.com/pk.svg", code: "PK", lat: 30.3753, lng: 69.3451),
  CountryModelData(name: "Palau", flag: "https://flagcdn.com/pw.svg", code: "PW", lat: 7.5149, lng: 134.5825),
  CountryModelData(name: "Panama", flag: "https://flagcdn.com/pa.svg", code: "PA", lat: 8.5375, lng: -80.7821),
  CountryModelData(name: "Papua New Guinea", flag: "https://flagcdn.com/pg.svg", code: "PG", lat: -6.314993, lng: 143.95555),
  CountryModelData(name: "Paraguay", flag: "https://flagcdn.com/py.svg", code: "PY", lat: -23.4425, lng: -58.4438),
  CountryModelData(name: "Peru", flag: "https://flagcdn.com/pe.svg", code: "PE", lat: -9.19, lng: -75.0152),
  CountryModelData(name: "Philippines", flag: "https://flagcdn.com/ph.svg", code: "PH", lat: 12.8797, lng: 121.774),
  CountryModelData(name: "Pitcairn Islands", flag: "https://flagcdn.com/pn.svg", code: "PN", lat: -24.7036, lng: -127.4398),
  CountryModelData(name: "Poland", flag: "https://flagcdn.com/pl.svg", code: "PL", lat: 51.9194, lng: 19.1451),
  CountryModelData(name: "Portugal", flag: "https://flagcdn.com/pt.svg", code: "PT", lat: 39.3999, lng: -8.2245),
  CountryModelData(name: "Puerto Rico", flag: "https://flagcdn.com/pr.svg", code: "PR", lat: 18.2208, lng: -66.5901),
  CountryModelData(name: "Qatar", flag: "https://flagcdn.com/qa.svg", code: "QA", lat: 25.3548, lng: 51.1839),
  CountryModelData(name: "Romania", flag: "https://flagcdn.com/ro.svg", code: "RO", lat: 45.9432, lng: 24.9668),
  CountryModelData(name: "Russia", flag: "https://flagcdn.com/ru.svg", code: "RU", lat: 55.7558, lng: 37.6176),
  CountryModelData(name: "Rwanda", flag: "https://flagcdn.com/rw.svg", code: "RW", lat: -1.9403, lng: 29.8739),
  CountryModelData(name: "Saint Kitts and Nevis", flag: "https://flagcdn.com/kn.svg", code: "KN", lat: 17.3577, lng: -62.782),
  CountryModelData(name: "Saint Lucia", flag: "https://flagcdn.com/lc.svg", code: "LC", lat: 13.9094, lng: -60.9783),
  CountryModelData(name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/pm.svg", code: "PM", lat: 46.8852, lng: -56.3149),
  CountryModelData(name: "Samoa", flag: "https://flagcdn.com/ws.svg", code: "WS", lat: -13.759, lng: -172.1046),
  CountryModelData(name: "San Marino", flag: "https://flagcdn.com/sm.svg", code: "SM", lat: 43.9333, lng: 12.45),
  CountryModelData(name: "Sao Tome and Principe", flag: "https://flagcdn.com/st.svg", code: "ST", lat: 0.1864, lng: 6.6131),
  CountryModelData(name: "Saudi Arabia", flag: "https://flagcdn.com/sa.svg", code: "SA", lat: 23.8859, lng: 45.0792),
  CountryModelData(name: "Senegal", flag: "https://flagcdn.com/sn.svg", code: "SN", lat: 14.6928, lng: -14.006),
  CountryModelData(name: "Serbia", flag: "https://flagcdn.com/rs.svg", code: "RS", lat: 44.0165, lng: 21.0059),
  CountryModelData(name: "Seychelles", flag: "https://flagcdn.com/sc.svg", code: "SC", lat: -4.6796, lng: 55.4915),
  CountryModelData(name: "Sierra Leone", flag: "https://flagcdn.com/sl.svg", code: "SL", lat: 8.4606, lng: -11.7799),
  CountryModelData(name: "Singapore", flag: "https://flagcdn.com/sg.svg", code: "SG", lat: 1.3521, lng: 103.8198),
  CountryModelData(name: "Tajikistan", flag: "https://flagcdn.com/tj.svg", code: "TJ", lat: 38.861, lng: 71.2761),
  CountryModelData(name: "Tanzania", flag: "https://flagcdn.com/tz.svg", code: "TZ", lat: -6.369028, lng: 34.888822),
  CountryModelData(name: "Thailand", flag: "https://flagcdn.com/th.svg", code: "TH", lat: 15.87, lng: 100.9925),
  CountryModelData(name: "Timor-Leste", flag: "https://flagcdn.com/tl.svg", code: "TL", lat: -8.8742, lng: 125.7275),
  CountryModelData(name: "Togo", flag: "https://flagcdn.com/tg.svg", code: "TG", lat: 7.4465, lng: 1.4025),
  CountryModelData(name: "Tonga", flag: "https://flagcdn.com/to.svg", code: "TO", lat: -21.178986, lng: -175.198242),
  CountryModelData(name: "Trinidad and Tobago", flag: "https://flagcdn.com/tt.svg", code: "TT", lat: 10.6918, lng: -61.2225),
  CountryModelData(name: "Tunisia", flag: "https://flagcdn.com/tn.svg", code: "TN", lat: 33.8869, lng: 9.5375),
  CountryModelData(name: "Turkey", flag: "https://flagcdn.com/tr.svg", code: "TR", lat: 38.9637, lng: 35.2433),
  CountryModelData(name: "Turkmenistan", flag: "https://flagcdn.com/tm.svg", code: "TM", lat: 38.9697, lng: 59.5563),
  CountryModelData(name: "Tuvalu", flag: "https://flagcdn.com/tv.svg", code: "TV", lat: -7.1095, lng: 179.194),
  CountryModelData(name: "Uganda", flag: "https://flagcdn.com/ug.svg", code: "UG", lat: 1.3733, lng: 32.2903),
  CountryModelData(name: "Ukraine", flag: "https://flagcdn.com/ua.svg", code: "UA", lat: 48.3794, lng: 31.1656),
  CountryModelData(name: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg", code: "AE", lat: 23.4241, lng: 53.8478),
  CountryModelData(name: "United Kingdom", flag: "https://flagcdn.com/gb.svg", code: "GB", lat: 55.3781, lng: -3.436),
  CountryModelData(name: "United States", flag: "https://flagcdn.com/us.svg", code: "US", lat: 37.0902, lng: -95.7129),
  CountryModelData(name: "United States Virgin Islands", flag: "https://flagcdn.com/vi.svg", code: "VI", lat: 18.3358, lng: -64.8963),
  CountryModelData(name: "Uruguay", flag: "https://flagcdn.com/uy.svg", code: "UY", lat: -32.5228, lng: -55.7658),
  CountryModelData(name: "Uzbekistan", flag: "https://flagcdn.com/uz.svg", code: "UZ", lat: 41.3775, lng: 64.5853),
  CountryModelData(name: "Vanuatu", flag: "https://flagcdn.com/vu.svg", code: "VU", lat: -15.3767, lng: 167.247),
  CountryModelData(name: "Vatican City", flag: "https://flagcdn.com/va.svg", code: "VA", lat: 41.9029, lng: 12.4534),
  CountryModelData(name: "Venezuela", flag: "https://flagcdn.com/ve.svg", code: "VE", lat: 6.4238, lng: -66.5897),
  CountryModelData(name: "Vietnam", flag: "https://flagcdn.com/vn.svg", code: "VN", lat: 14.0583, lng: 108.2772),
  CountryModelData(name: "Wallis and Futuna", flag: "https://flagcdn.com/wf.svg", code: "WF", lat: -13.768, lng: -177.1561),
  CountryModelData(name: "Yemen", flag: "https://flagcdn.com/ye.svg", code: "YE", lat: 15.5522, lng: 48.5164),
  CountryModelData(name: "Zambia", flag: "https://flagcdn.com/zm.svg", code: "ZM", lat: -13.1339, lng: 27.8493),
  CountryModelData(name: "Zimbabwe", flag: "https://flagcdn.com/zw.svg", code: "ZW", lat: -19.0154, lng: 29.1549),
];